Global:
  debug: False
  use_gpu: true
  distributed: true
  epoch_num: 40
  log_smooth_window: 20
  # pretrained_model: /kaggle/temp/weights/latest
  print_batch_step: 20
  save_model_dir: /kaggle/working/rec
  save_epoch_step: 2
  eval_batch_step: [0, 3000]
  character_dict_path: ppocr/utils/dict/casia_hwdb_dict.txt
  char_num: &char_num 10852
  max_text_length: &max_len 1
  use_space_char: false
  image_shape: [3, 48, 48]

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    values: [0.00128, 0.000128, 0.0000128]
    decay_epochs: [6, 16]
    warmup_epoch: 1
  regularizer: { name: L2, factor: 3.0e-05 }

Architecture:
  model_type: cls
  algorithm:  CLS

  Backbone:
    name: SVTRNet
    model_name: base
    in_chans: 3
    out_channels: 384
    img_size: [48, 48]
    patch_size: [4, 2]
    out_char_num: 6 

  Head:
    name: ClsHead
    in_channels: 384
    class_dim: *char_num
    fc_decay: 1.0e-5

Loss:
  name: ClsLoss

Metric:
  name: ClsMetric
  main_indicator: acc

PostProcess:
  name: ClsPostProcess
  character_dict_path: ppocr/utils/dict/casia_hwdb_dict.txt

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/temp/extracted_data
    label_file_list:
      - ./train_labels/converted_casia_hwdb_train.txt
      # - ./train_labels/nom_train_data_1.txt
      # - ./train_labels/nom_train_data_2.txt
      # - ./train_labels/nom_train_data_3.txt
    transforms:
      - DecodeImage: { img_mode: BGR, channel_first: false }
      - ClsLabelEncode:
          label_list: ppocr/utils/dict/casia_hwdb_dict.txt
      - SVTRRecResizeImg: { image_shape: [3, 48, 48], pad: false }
      - KeepKeys: { keep_keys: [image, label] }
  loader:
    shuffle: true
    batch_size_per_card: 512
    drop_last: true
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/temp/extracted_data
    label_file_list:
      - ./train_labels/converted_casia_hwdb_test.txt
      # - ./train_labels/converted_nom_test_data.txt
    transforms:
      - DecodeImage: { img_mode: BGR, channel_first: false }
      - ClsLabelEncode:
          label_list: ppocr/utils/dict/casia_hwdb_dict.txt
      - SVTRRecResizeImg: { image_shape: [3, 48, 48], pad: false }
      - KeepKeys: { keep_keys: [image, label] }
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 512
    num_workers: 2