Global:
  debug: False
  use_gpu: true
  distributed: true
  epoch_num: 40
  log_smooth_window: 20
  print_batch_step: 20
  # checkpoints: /kaggle/temp/weights/latest
  save_model_dir: /kaggle/working/rec
  save_epoch_step: 2
  eval_batch_step: [0, 3000]
  character_dict_path: ppocr/utils/dict/casia_hwdb_dict.txt
  char_num: &char_num 10852
  max_text_length: &max_text_length 1
  use_space_char: false
  image_shape: [3, 48, 48]
  infer_mode: false
  save_res_path: ./output/rec/predicts_svtr_large_nom.txt

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 1.0e-08
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed char_node_embed pos_node_embed char_pos_embed vis_pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 8

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null    
  Backbone:
    name: SVTRNet
    img_size: [48, 48]
    out_char_num: 6  # W//8 for 48 width
    out_channels: 512
    patch_merging: Conv
    embed_dim: [192, 256, 512]
    depth: [6, 6, 9]
    num_heads: [6, 8, 16]
    mixer: ['Conv','Conv','Conv','Conv','Conv','Conv','Conv','Conv','Conv','Global','Global','Global','Global','Global','Global','Global','Global','Global','Global','Global','Global']
    local_mixer: [[5, 5], [5, 5], [5, 5]]
    last_stage: False
    prenorm: True
  Head:
    name: CTCHeadTLast
    in_channels: 512  # Match the backbone out_channels
    fc_decay: 1.0e-5
    out_channels: *char_num

Loss:
  name: CTCLoss

PostProcess:  
  name: CTCLabelDecodeTopK
  character_dict_path: ppocr/utils/dict/casia_hwdb_dict.txt
  use_space_char: false
  k: 5

Metric:
  name: RecMetricTopK
  main_indicator: acc
  ignore_space: false

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/temp/extracted_data
    ext_op_transform_idx: 1
    label_file_list:
      - ./train_labels/converted_casia_hwdb_train.txt
      # - ./train_labels/nom_train_data_1.txt
      # - ./train_labels/nom_train_data_2.txt
      # - ./train_labels/nom_train_data_3.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.25
        ext_data_num: 2
        image_shape: [48, 48, 3]
    - RecAug:
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 48]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 256  # Reduced due to larger model
    drop_last: true
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/temp/extracted_data
    label_file_list:
      - ./train_labels/converted_casia_hwdb_test.txt
      # - ./train_labels/converted_nom_test_data.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 48]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 256
    num_workers: 2 