Global:
  use_amp: true
  use_gpu: true
  distributed: true
  epoch_num: 40
  log_smooth_window: 20
  # checkpoints: /kaggle/temp/weights/latest
  print_batch_step: 20
  save_model_dir: /kaggle/working/rec
  save_epoch_step: 1
  eval_batch_step: [0, 2000]
  character_dict_path: ppocr/utils/dict/casia_hwdb_dict.txt
  char_num: &char_num 10852
  max_text_length: &max_len 1
  use_space_char: false
  image_shape: [3, 48, 48]
  d2s_train_image_shape: [3, 48, 48]

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    values: [0.00096, 0.000096, 0.0000096]
    decay_epochs: [6, 16]
    warmup_epoch: 1
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: "rec"
  algorithm: CRNN
  Backbone:
    name: PPHGNetV2_B4
    text_rec: true
  Head:
    name: CTCHead
    in_channels: 2048
    fc_decay: 1.0e-5
    out_channels: *char_num

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode
  character_dict_path: ppocr/utils/dict/casia_hwdb_dict.txt
  use_space_char: false

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: false

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/temp/extracted_data
    label_file_list:
      # - ./train_labels/test_han_train_data_converted.txt
      # - ./train_labels/final_nom_train_data_converted.txt
      # - ./train_labels/nom_train_data_1.txt
      # - ./train_labels/nom_train_data_2.txt
      # - ./train_labels/nom_train_data_3.txt
      - ./train_labels/converted_casia_hwdb_train.txt
    ext_op_transform_idx: 1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.25
          ext_data_num: 2
          image_shape: [48, 48, 3]
      - RecAug:
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 48, 48]
          pad: false
      - KeepKeys:
          keep_keys: [image, label, length]
  loader:
    shuffle: true
    batch_size_per_card: 384
    drop_last: true
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/temp/extracted_data
    label_file_list:
      # - ./train_labels/test_han_test_data_converted.txt
      # - ./train_labels/final_nom_test_data_converted.txt
      # - ./train_labels/converted_nom_test_data.txt
      - ./train_labels/converted_casia_hwdb_test.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 48, 48]
          pad: false
      - KeepKeys:
          keep_keys: [image, label, length]
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 384
    num_workers: 2
